# Generated by Django 3.1.14 on 2023-11-25 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventnew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventnew',
            name='title',
        ),
        migrations.AddField(
            model_name='eventnew',
            name='date',
            field=models.DateTimeField(default=datetime.date(2023, 11, 25)),
        ),
    ]
