# Generated by Django 3.1.14 on 2023-11-25 08:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20231125_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='anons',
            field=models.CharField(default='', max_length=100, verbose_name='Anons'),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='eventnew',
            name='anons',
            field=models.CharField(default='', max_length=300, verbose_name='Anons'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 25, 8, 19, 12, 854761, tzinfo=utc), verbose_name='Date'),
        ),
    ]
