# Generated by Django 3.1.14 on 2023-11-25 09:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20231125_1819'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventNew',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 25, 9, 45, 20, 528556, tzinfo=utc), verbose_name='Date'),
        ),
    ]
