# Generated by Django 3.1.14 on 2023-12-02 08:54

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0008_auto_20231125_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='creator_id',
            field=models.ForeignKey(default=1, on_delete=models.SET(1), to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 8, 54, 48, 397518, tzinfo=utc), verbose_name='Date'),
        ),
    ]
