# Generated by Django 3.2.23 on 2023-12-06 01:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20231206_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 6, 1, 10, 43, 820170, tzinfo=utc), verbose_name='Date'),
        ),
    ]
