# Generated by Django 3.1.14 on 2023-12-15 02:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20231207_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 15, 2, 50, 57, 386389, tzinfo=utc), verbose_name='Date'),
        ),
    ]
